# -*- coding: utf-8 -*-
"""
Configuration file for the ORB Trading Bot.
"""

import MetaTrader5 as mt5
from datetime import time

# --- MT5 CONNECTION DETAILS ---
MT5_LOGIN = 40682668
MT5_PASSWORD = "R0sycheeks@1"
MT5_SERVER = "Deriv-Demo"
MT5_PATH = r"C:\Program Files\MetaTrader 5 Terminal\terminal64.exe"

# --- BACKTESTING ---
INITIAL_EQUITY_BACKTEST = 100.0
INITIAL_EQUITY_OPTIMIZER = 100.0
INITIAL_EQUITY_WALK_FORWARD = 100.0

# --- GENERAL TRADING PARAMETERS ---
LOT_SIZE = 0.1
MAGIC_NUMBER = 20240910
MARKET_TIMEZONE = 'America/New_York'

# Timeframe for the opening range candle.
# Options: mt5.TIMEFRAME_M1, mt5.TIMEFRAME_M5, mt5.TIMEFRAME_M15, mt5.TIMEFRAME_M30, mt5.TIMEFRAME_H1, etc.
ORB_TIMEFRAME = mt5.TIMEFRAME_M15

# --- US MARKET SETTINGS ---
TRADE_US_MARKETS = True
US_MARKET_OPEN_TIME = '09:30'
US_SYMBOLS = ['Wall Street 30', 'US SP 500', 'US Tech 100', 'AAPL', 'MSFT', 'TSLA', 'AMZN']

# --- EUROPEAN MARKET SETTINGS ---
TRADE_EUROPEAN_MARKETS = True
EUROPEAN_MARKET_OPEN_TIME = '03:00' # 8:00 AM London / 9:00 AM Frankfurt in NY time (approx)
EUROPEAN_SYMBOLS = ['Germany 40', 'UK 100']

# --- 24-HOUR MARKET SETTINGS (FOREX, CRYPTO, COMMODITIES) ---
TRADE_24_HOUR_MARKETS = True
# Strategy for 24-hour markets: 'MIDNIGHT' or 'SESSION'
OPENING_RANGE_METHOD_24_HOUR = 'SESSION' 

# If 'SESSION', define the session start times (in NY time)
SESSION_OPEN_TIMES = {
    'LONDON': '03:00',
    'NEW_YORK': '08:00',
}

FOREX_SYMBOLS = ['USDMXN']
CRYPTO_SYMBOLS = ['BTCUSD']
COMMODITY_SYMBOLS = ['XAUUSD', 'XAGUSD', 'XPTUSD', 'UK Brent Oil', 'US Oil']

# --- SYMBOL LIST CONSTRUCTION ---
SYMBOLS = []
if TRADE_US_MARKETS:
    SYMBOLS.extend(US_SYMBOLS)
if TRADE_EUROPEAN_MARKETS:
    SYMBOLS.extend(EUROPEAN_SYMBOLS)
if TRADE_24_HOUR_MARKETS:
    SYMBOLS.extend(FOREX_SYMBOLS)
    SYMBOLS.extend(CRYPTO_SYMBOLS)
    SYMBOLS.extend(COMMODITY_SYMBOLS)

# --- STRATEGY SETTINGS ---
RISK_REWARD_RATIO_STANDARD = 2.0
RISK_REWARD_RATIO_REVERSAL = 3.0
TRADE_REVERSAL_STRATEGY = True

# --- RISK MANAGEMENT ---
RISK_PER_TRADE_PERCENT = 1.0
# Options: "FIXED", "RISK_PERCENT", "MIN_LOT"
DEFAULT_LOT_SIZE_STRATEGY = "RISK_PERCENT" 
MAX_OPEN_TRADES_GLOBAL = 1
DEFAULT_MAX_STOP_LOSS_PIPS = 100
# Custom max stop loss pips for specific symbols (overrides the default)
CUSTOM_MAX_STOP_LOSS_PIPS = {
    # "BTCUSD": 500,
    # "US SP 500": 50
}
# Custom lot sizes for specific symbols (overrides the default strategy)
CUSTOM_LOT_SIZES = {
    # "BTCUSD": 0.01,
    # "US SP 500": 0.1
}

# --- NOTIFICATIONS ---
TELEGRAM_ENABLED = True
TELEGRAM_BOT_TOKEN = "8239015430:AAGTaCWybetULbE09KRqjqIwNXcn7kCjEtQ"
TELEGRAM_CHAT_ID = "5116546179"


# --- OPTIMIZATION ---
OPTIMIZATION_PARAMS = {
    'US SP 500': {
        'ORB_TIMEFRAME': [mt5.TIMEFRAME_M15, mt5.TIMEFRAME_M30],
        'RISK_REWARD_RATIO_STANDARD': [2, 3, 4, 5],
        'RISK_REWARD_RATIO_REVERSAL': [2, 3, 4, 5],
    },
    'Germany 40': {
        'ORB_TIMEFRAME': [mt5.TIMEFRAME_M15, mt5.TIMEFRAME_M30],
        'RISK_REWARD_RATIO_STANDARD': [2, 3, 4, 5],
        'RISK_REWARD_RATIO_REVERSAL': [2, 3, 4, 5],
    },
    'BTCUSD': {
        'ORB_TIMEFRAME': [mt5.TIMEFRAME_H1, mt5.TIMEFRAME_H4],
        'RISK_REWARD_RATIO_STANDARD': [2, 3, 4, 5],
        'RISK_REWARD_RATIO_REVERSAL': [2, 3, 4, 5],
    }
}

# --- PRE-MARKET FETCH SETTINGS ---
PRE_MARKET_FETCH_ENABLED = False
PRE_MARKET_FETCH_MINUTES = {
    'US': 10,
    'EUROPEAN': 10,
    '24_HOUR': 10 # Before London, NY, and NY PM sessions
}
